# Generated by Django 3.1 on 2020-08-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cow_TextModel',
            new_name='CowTextModel',
        ),
    ]
